language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update -n

install:
  - composer install -n

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

sudo: false
cache:
  - directories:
    - vendor/
